### ISSUE TITLE
Please update this addon 

### ISSUE THREAD

**Issue by NiKola-UE** [abdallah-hader/typing_settings#2]
I have been using this addon for a while because I like it, but the problem is that it has become incompatible with the latest version of NVDA. Yes, it can work without problems, but when updating and running the program, there may be errors due to risk warnings... 

I would also like this addon to appear in the official NVDA Addon Store, which is still easier than looking for it externally. 

Thanks in advance.

**Comment by abdallah-hader** [comment]
hello, soon i will update this, sorry for late reply

**Comment by NiKola-UE** [comment]
No problem, thanks for responding. But I would like this addon to be found in the Addon Store if possible. It still works fine, but NVDA is annoying with incompatibility warnings, although maybe some new options can be added. I also mentioned you in 
[this place ](https://github.com/ahmedthebest31/navsounds/issues/12) 
because it seemed to me that these two addons could somehow be combined, but it was not my intention to cause any confusion. 



I won't go into it here, but I think the Advanced Notepad also needs an update.

**Comment by abdallah-hader** [comment]
Sure, I will update it soon and put it on addons-store.
As for Advanced Notepad, I don't know if I will update it or not.

**Comment by NiKola-UE** [comment]
Everything is fine, you don't have to rush. 








As for the Advanced Notepad, it should only add support for some other formats and Unicode, because documents with languages ​​that use them (among them is Serbo-Croatian, which I speak) do not load very well.

**Comment by NiKola-UE** [comment]
Dear @abdallah-hadar, 










Once again, there's no need to rush the update. Despite the supposed incompatibility, the addon works just fine and I'm currently using it together with "Navigation Sound", which is a great combination for me. However, when there is an update, try to add more sound schemes to cover different actions on movement like booting, loading, opening, etc.; so not only for text input. Personally, I would like it if there were such sounds as Braille machines, old printers, landline phones, etc. 









And you don't need to update the Advanced Notepad at all, because there are already much more advanced and ewen better programs that are published much more often, such as 
[Rizonesoft's Notepad3 ](https://github.com/rizonesoft/Notepad3) 
or 
[Notepad-plus-plus, ](https://github.com/notepad-plus-plus/notepad-plus-plus), 
and on which you should perhaps cooperate if you it suited you. 






Thanks.

**Comment by abdallah-hader** [comment]
Welcome, as for the compatibility of the add-on, I have already updated it. As for the sounds, one of the users sent me a wonderful mix of sounds. I will add it later, but can you tell me what you mean by adding sounds for opening and loading?

**Comment by NiKola-UE** [comment]
Hello, 






I apologize if I am late in replying. 





Well, I mostly compare this addon with "Navigation Sound", so I thought that there could be more sound schemes that would be used in parallel with these existing ones, but independently of them. In particular, that different sounds are made only when you type some text, but also when you open a program, load a page and command, when I move something or navigating into the any program, etc.; if you understand what I mean. For example, when this page refreshes after I publish this comment, when I open a text editor, when a warning or notification appears on the screen, when I navigate in a program with tabs and arrows, when I surf, etc. Of course, not all at once. And add those strange sound schemes in parallel to this addon as one of the new options, so that those who want it, and I want to, can use them. 







Kudos for the update, if only the latest version would still officially appear in the Addon Store. Thank you

**Comment by NiKola-UE** [comment]
@abdallah-hader, 

I will close this issue because there is nothing more to say and I don't want to burden you anymore. 








So, only this latest version needs to be added to the official NVDA Addon Store. The older version has been added, but the new one still hasn't. 



I believe you will also add the scheme of those strange sounds. 



By additional sounds, I simply meant that some sounds are heard after opening a program or loading a page been finished, if you understand me better now. 





I wish you the best. Thank you.
